[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pastasoss"
version = "0.1.0"
authors = [
    {name = "Tyler Baines", email = "tbaines@stsci.edu"},
]
description = "My package description"
readme = "README.md"
requires-python = ">=3.9"


[tool.setuptools]
# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
packages = ["pastasoss"]
include-package-data = true





